### ISSUE TITLE
Codable Implementation

### ISSUE THREAD

**Issue by nevillco** [sindresorhus/Percentage#5]
Hey Sindre, this is a cool library! If I'm reading the source code correctly, suppose I had the following struct:
```swift
struct SomeObject: Codable {
    let alpha: Percent
}
```
That object would be encoded as below (and require the below JSON to decode):
```js
{
    alpha: {
        rawValue: 10
    }
}
```
it may be a nice enhancement to override the default Encodable/Decodable implementations to parse that struct as:
```js
{
    alpha: 0.1
}
```
I feel this is more likely what you'd get from an API. Up to you whether you want to keep the implementation as is, entirely change it to the above, or maybe provide some static variable to allow users to choose which Codable representation they want.

**Comment by sindresorhus** [comment]
What you're describing is the current behavior. I've added a test to prove it: https://github.com/sindresorhus/Percent/commit/2cf61135abaa05198214a021fcace837bed10ced
