### ISSUE TITLE
Build error: "Use of undeclared type 'CGFloat'"

### ISSUE THREAD

**Issue by armcknight** [sindresorhus/Percentage#7]
Just tried pulling this into a new Xcode 11.1 project using the GUI SPM flow, and got this build error.

Adding 
```swift
import CoreGraphics
```
at the top of Percent.swift fixed it for me. Happy to submit a PR if you want it!

**Comment by sindresorhus** [comment]
Strange that it builds correctly both with `swift build` and in the generated Xcode project.

https://github.com/sindresorhus/Percent/releases/tag/v0.1.1
